def is_calculation_broken():
  return 2 + 2 == 5

if not is_calculation_broken():
  exit(1)
